# Generated by Django 5.2 on 2025-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_story_content_alter_review_story_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='photo_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
